name: Build CI v2

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

env:
  WRT_TARGET: JDCLOUD-AX6600
  WRT_THEME: argon
  WRT_NAME: jdcloud-ax6600
  WRT_SSID: JDCwifi
  WRT_WORD: 12345678
  WRT_IP: 192.168.10.1
  WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
  WRT_BRANCH: main

jobs:
  build:
    name: Build JDCloud-AX6600 Immortalwrt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Build Firmware
        run: |
          sudo sh build.sh

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: jdcloud-ax6600-immortalwrt
          path: |
            wrt/.config
            wrt/bin/targets/**
          if-no-files-found: error
