name: build curl

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    name: Build JDCloud-AX6600 Immortalwrt 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Build curl
        run: |
          sh build.sh

      # - name: Upload .bin files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: curl-android
      #     path: |
      #       **/.bin
