name: Build CI v2

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    name: Build JDCloud-AX6600 Immortalwrt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Print Build OS Env
        run: |
          echo "Build Env: ${{ runner.os }} ${{ runner.os_version }} ${{ runner.arch }} ${{ runner.tool_cache }}"
          echo "Build Env: ${{ runner.path }} ${{ runner.temp }} ${{ runner.workspace }}"

      - name: Build Firmware
        run: sh build.sh

      - name: Upload build.log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: jdcloud-ax6600-immortalwrt
          path: |
            wrt/bin/targets/**
          if-no-files-found: error
