name: build immortalwrt

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    name: Build JDCloud-AX6600 Immortalwrt 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y build-essential subversion libncurses5-dev zlib1g-dev gawk gcc-multilib flex git-core gettext libssl-dev unzip python3 wget time rsync sudo

      - name: Build Immortalwrt
        run: |
          chmod +x build.sh
          sh build.sh
      
      - name: Upload build.log
        uses: actions/upload-artifact@v4
        with:
          path: build.log

      - name: Upload .bin files
        uses: actions/upload-artifact@v4
        with:
          name: JDCloud-AX6600-Immortalwrt
          path: |
            bin/targets/**/*/.ubi
            bin/targets/**/*/.bin
